server:
  port: 8081

spring:
  datasource:
    username: postgres
    password: 1234

    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.demo.entity


logging:
  level:
    com.example.demo.mapper: debug
